# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-31T03:33:52Z"
  labels:
    app: api
  name: api
spec:
  containers:
  - image: localhost/fetch-api-image:latest
    name: fetch-api-container
    ports:
    - containerPort: 8001
      hostPort: 8002
    tty: true
    env:
    - name: APP_NAME
      valueFrom:
        secretKeyRef:
          name: local-secrets
          key: APP_NAME
  restartPolicy: Always

