---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: fetch
spec:
  # reconsider rss allocation further down if increasing replicas
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: git.example.com:4567/fetch/inventory_service/prod:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8001
          # reconsider rss allocation if increasing replicas
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
              ephemeral-storage: "200Mi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
              ephemeral-storage: "500Mi"
      imagePullSecrets:
      - name: gitlab-api-2023
