"""Adding Location Generation

Revision ID: 2024_10_07_10:08:23
Revises: 2024_08_06_21:32:59
Create Date: 2024-10-07 14:08:23.704511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2024_10_07_10:08:23"
down_revision: Union[str, None] = "2024_08_06_21:32:59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shelf_positions",
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=75), nullable=True
        ),
    )
    op.add_column(
        "shelf_positions",
        sa.Column(
            "internal_location",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
    )
    op.create_unique_constraint("uq_shelf_positions_location", "shelf_positions",
                                ["internal_location"])
    op.create_unique_constraint("uq_shelf_positions_internal_location", "shelf_positions",
                                ["location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_shelf_positions_internal_location", "shelf_positions", type_="unique")
    op.drop_constraint("uq_shelf_positions_location", "shelf_positions", type_="unique")
    op.drop_column("shelf_positions", "internal_location")
    op.drop_column("shelf_positions", "location")
    # ### end Alembic commands ###
