"""shelf_location

Revision ID: 2024_11_24_21:51:13
Revises: 2024_11_23_19:52:08
Create Date: 2024-11-24 21:51:13.614578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2024_11_24_21:51:13'
down_revision: Union[str, None] = '2024_11_23_19:52:08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelves', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=175), nullable=True))
    op.add_column('shelves', sa.Column('internal_location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_unique_constraint("uq_shelves_internal_loc", 'shelves', ['internal_location'])
    op.create_unique_constraint("uq_shelves_loc", 'shelves', ['location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_shelves_internal_loc", 'shelves', type_='unique')
    op.drop_constraint("uq_shelves_loc", 'shelves', type_='unique')
    op.drop_column('shelves', 'internal_location')
    op.drop_column('shelves', 'location')
    # ### end Alembic commands ###
