"""item_scanned_for_accession

Revision ID: 2024_03_15_15:11:16
Revises: 2024_03_15_14:56:00
Create Date: 2024-03-15 14:11:16.058098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2024_03_15_15:11:16'
down_revision: Union[str, None] = '2024_03_15_14:56:00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('scanned_for_accession', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'scanned_for_accession')
    # ### end Alembic commands ###
