"""Updating barcode table

Revision ID: 2024_07_29_20:03:23
Revises: 2024_07_27_15:55:29
Create Date: 2024-07-30 00:03:23.029713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_07_29_20:03:23"
down_revision: Union[str, None] = "2024_07_27_15:55:29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("barcodes", sa.Column("withdrawn", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("barcodes", "withdrawn")
    # ### end Alembic commands ###
