"""Adding Shelves available space

Revision ID: 2024_08_05_22:50:01
Revises: 2024_07_31_20:51:58
Create Date: 2024-08-06 02:50:01.113399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_08_05_22:50:01"
down_revision: Union[str, None] = "2024_07_31_20:51:58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shelves", sa.Column("available_space", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shelves", "available_space")
    # ### end Alembic commands ###
