"""Add building table

Revision ID: e3e5218866f6
Revises: 
Create Date: 2023-10-09 00:49:56.312197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e3e5218866f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    # ### end Alembic commands ###
