"""Add module tables

Revision ID: fb524ceb9a37
Revises: e3e5218866f6
Create Date: 2023-10-09 12:02:49.946000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fb524ceb9a37'
down_revision: Union[str, None] = 'e3e5218866f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('module_number_id', sa.Integer(), nullable=False),
    sa.Column('update_dt', sa.DateTime(), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['module_number_id'], ['module_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'module_number_id', name='uq_building_id_module_number_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modules')
    op.drop_table('module_numbers')
    # ### end Alembic commands ###
